In [1]:
import pandas as pd

Choosing data in a Series
Let’s create a simple series and store it in a variable named “series_1”.

In [2]:
series_1 = pd.Series([2,3,4,5,6])
series_1

0    2
1    3
2    4
3    5
4    6
dtype: int64

The output of the series shows index 01,2,3,4 on the left column. We can use these index values to call a data value in the series.

Series - Selecting data based on the index

If we want to get the value stored at Series index position 3, we would type the following code, and Pandas will return the value 5 stored at index value 3.

In [3]:
series_1[3]

np.int64(5)

Series — Re-indexing a series to make things easier

Pandas also allows you to create an index with string (text) values. In some cases, it might be easier to call an index position by its name.

So let’s start a series where our index will be candy names, and the data will reflect candy quantities.

In [4]:
sale = pd.Series([500,85000,40000,9600,100000], 
                 index=['Cookie', 'Choco','Toothpaste','Soap','Toffee'
                        ])
sale

Cookie           500
Choco          85000
Toothpaste     40000
Soap            9600
Toffee        100000
dtype: int64

Now let’s apply the same approach, but this time to the new index we have created.

In [5]:
sale.Toffee

np.int64(100000)

Choosing data in Data frame
As discussed before, a data frame is a two-dimensional data structure with rows and columns. The Rows and columns in a data frame are indexed separately and can be used to select the data we need for our analysis.

Let’s create a simple data frame with three columns state, year and pop (population).

In [7]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],'year': [2000, 2001, 2002, 2001, 2002, 2003],'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
data = pd.DataFrame(data)
data

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

Selecting columns in a data frame

In our example, we will select the column ‘state’ from the data frame, and the result will show us all the data stored in that column. There are two ways to select the column.

Dot notation method

In [8]:
data.state

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [8]:
data.state

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

Choosing either method is a personal choice, but there are some caveats that one should keep in mind.

Dot notation has some limitations:

It does not work if the column name has spaces.
The column name is a python or pandas keyword.
The column name is an integer.
You can not add a new column name with do notation.
Now let’s see a practical example of why dot notation is limited in some instances. We aim to select a pop (population) column with dot notation.

In [9]:
data.pop

<bound method DataFrame.pop of     state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2>

This output is not what we expected because ‘pop’ is a python keyword/function.
In this scenario, using the Index Operator method would be appropriate. Dot notation method cannot process the word pop as it is a python keyword and displays the column selection accurately.

In [10]:
data['pop']

0    1.5
1    1.7
2    3.6
3    2.4
4    2.9
5    3.2
Name: pop, dtype: float64

In summary, it is a matter of choice; some consider Dot notation to be convenient as it takes only one dot compared to [“ “] four extra characters.

We also can select multiple columns by defining a list of column names.

In [11]:
data[['pop', 'state']]

   pop   state
0  1.5    Ohio
1  1.7    Ohio
2  3.6    Ohio
3  2.4  Nevada
4  2.9  Nevada
5  3.2  Nevada

Keep in mind that the order defined in the list is shown in the output. And it might be different from the order in the original dataframe.

Selecting data frame rows and columns using .iloc and loc

Pandas loc and iloc methods are two top choices when selecting data using rows and columns.

loc is label-based. You can select rows with index, but only labels are used to choose columns.
iloc is an integer location-based. We can select only rows and columns with their index positions.
The basic usage of loc and iloc is df.iloc[rows , columns] and df.loc[rows, columns]. The difference is passing the index position or labels.

We will use a real-world data set called Stack Overflow Annual Developer Survey for this section. It can be found here. (Choose the year 2020 data set)

Let’s load the entire data set with all 61 columns.

In [12]:
df = pd.read_csv('../survey_results_public.csv')
df

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49118,49119,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,9.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0
49119,49120,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc.)",13.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49120,49121,I am a developer by profession,25-34 years old,"Secondary school (e.g. American high school, G...",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","No, I didn't spend time learning in the past year",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49121,49122,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,None of the above;Engaged in paid work (20-29 ...,10.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0
49122,49123,I am a developer by profession,25-34 years old,Some college/university study without earning ...,Employed,None of the above,10.0,"No, I am not new to coding and did not learn n...",NaN,"No, I learned something that was not related t...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0

Or, for simplicity, we can also load the data set with just the columns we need. In this case, we only want the Age, ConvertedComp, Country, LanguageWorkedWith and YearsCode columns. The total number of columns are in the data set is 61.

In [15]:
df = pd.read_csv('../survey_results_public_2020.csv', usecols=['Age','ConvertedComp', 'Country', 'LanguageWorkedWith', 'YearsCode'])
df

,Age,ConvertedComp,Country,LanguageWorkedWith,YearsCode
0,NaN,NaN,Germany,C#;HTML/CSS;JavaScript,36
1,NaN,NaN,United Kingdom,JavaScript;Swift,7
2,NaN,NaN,Russian Federation,Objective-C;Python;Swift,4
3,25.0,NaN,Albania,NaN,7
4,31.0,NaN,United States,HTML/CSS;Ruby;SQL,15
...,...,...,...,...,...
64456,NaN,NaN,United States,NaN,10
64457,NaN,NaN,Morocco,Assembly;Bash/Shell/PowerShell;C;C#;C++;Dart;G...,NaN
64458,NaN,NaN,Viet Nam,NaN,NaN
64459,NaN,NaN,Poland,HTML/CSS,NaN
64460,NaN,NaN,Spain,C#;HTML/CSS;Java;JavaScript;SQL,NaN

iloc

Let’s get the value stored at row number 1 and column number 2 using iloc.

In [16]:
df.iloc[1, 2]

'United Kingdom'

Selecting multiple rows can be difficult; a shorter way is to choose a range of index positions. Here we choose a slice of rows for 2 to 9 using the range (:).

Remember that using the range of rows will have the start index as inclusive, and the end index is exclusive. So it will give values from rows 2 to 8 of column number 2.

In [17]:
df.iloc[2:9, 2]

2    Russian Federation
3               Albania
4         United States
5               Germany
6                 India
7         United States
8               Tunisia
Name: Country, dtype: object

Let’s choose data in all five columns for rows 1 to 49999.

In [18]:
df_subset = df.iloc[1:50000]
df_subset

,Age,ConvertedComp,Country,LanguageWorkedWith,YearsCode
1,NaN,NaN,United Kingdom,JavaScript;Swift,7
2,NaN,NaN,Russian Federation,Objective-C;Python;Swift,4
3,25.0,NaN,Albania,NaN,7
4,31.0,NaN,United States,HTML/CSS;Ruby;SQL,15
5,NaN,NaN,Germany,HTML/CSS;Java;JavaScript,6
...,...,...,...,...,...
49995,29.0,27864.0,Croatia,HTML/CSS;JavaScript;PHP;SQL;TypeScript,8
49996,NaN,112456.0,United Kingdom,Bash/Shell/PowerShell;Python,40
49997,56.0,131844.0,United Kingdom,Bash/Shell/PowerShell;C#;HTML/CSS;Java;JavaScr...,41
49998,42.0,82000.0,United States,Java;JavaScript;SQL,26
49999,NaN,53184.0,Germany,HTML/CSS;JavaScript;PHP;SQL,20

Here we can observe that column name is not mandatory, and we have to write index position 50000 to select rows up to number 49999.

loc

As discussed loc function can use either index position or label for rows. So let’s select data in column LanguageWorkedWith from 500 to 550.

But wait a minute, why did we not write row 551 to get row 550 in the loc function? Here it is important to remember the loc function works on labels, even integer-based locations treated as labels. That’s why the output we will get from 550 to 550, unlike the iloc function from 550 to 549.

In [19]:
df.loc[500:550, 'LanguageWorkedWith']

500                                          C#;HTML/CSS
501            Bash/Shell/PowerShell;C#;Dart;Java;Kotlin
502                                                  SQL
503       C++;HTML/CSS;Java;JavaScript;Python;TypeScript
504               C#;HTML/CSS;Java;JavaScript;Python;SQL
505                C;C++;HTML/CSS;Java;JavaScript;Python
506                                               Python
507                                  HTML/CSS;JavaScript
508                   Bash/Shell/PowerShell;C;C++;Python
509                             HTML/CSS;JavaScript;Ruby
510                         Bash/Shell/PowerShell;Python
511                C#;HTML/CSS;JavaScript;SQL;TypeScript
512         JavaScript;Kotlin;Python;Ruby;SQL;TypeScript
513    Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;K...
514       Bash/Shell/PowerShell;C#;JavaScript;Python;SQL
515    Bash/Shell/PowerShell;C#;Go;Java;Kotlin;Python...
516                                               Python
517                Bash/Shell/PowerShell;Java;Python;SQL
518                C#;HTML/CSS;JavaScript;SQL;TypeScript
519                C#;HTML/CSS;JavaScript;PHP;Python;SQL
520            Go;Haskell;HTML/CSS;JavaScript;TypeScript
521    Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;PHP;...
522               C++;HTML/CSS;JavaScript;PHP;Python;SQL
523               Bash/Shell/PowerShell;Python;R;SQL;VBA
524    Bash/Shell/PowerShell;C;C++;Go;HTML/CSS;Java;J...
525       Bash/Shell/PowerShell;HTML/CSS;JavaScript;Perl
526                           HTML/CSS;Java;Python;R;SQL
527    Bash/Shell/PowerShell;C++;HTML/CSS;JavaScript;...
528                       HTML/CSS;JavaScript;TypeScript
529                                                Swift
530    Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;S...
531                                          Java;Python
532        C#;Go;HTML/CSS;JavaScript;Ruby;SQL;TypeScript
533                                                    R
534                                      C#;HTML/CSS;SQL
535    Bash/Shell/PowerShell;C#;HTML/CSS;Java;JavaScr...
536                             C#;JavaScript;TypeScript
537    Bash/Shell/PowerShell;C;HTML/CSS;JavaScript;PH...
538                 C;C++;HTML/CSS;Java;JavaScript;R;SQL
539                               Java;JavaScript;Python
540           Bash/Shell/PowerShell;Go;HTML/CSS;Java;SQL
541                                                   C#
542               C#;Go;JavaScript;Python;SQL;TypeScript
543                       C#;HTML/CSS;JavaScript;PHP;SQL
544                          HTML/CSS;JavaScript;PHP;SQL
545                                                 Java
546    Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...
547                    Java;JavaScript;Kotlin;TypeScript
548    Bash/Shell/PowerShell;C;Go;HTML/CSS;Java;JavaS...
549                   HTML/CSS;JavaScript;PHP;Python;SQL
550                                    Objective-C;Swift
Name: LanguageWorkedWith, dtype: object

Let’s expand our selection to multiple rows and columns with the loc function.

In [20]:
df.loc[[1,2,3,4,5], ['Age', 'Country', 'ConvertedComp']]

    Age             Country  ConvertedComp
1   NaN      United Kingdom            NaN
2   NaN  Russian Federation            NaN
3  25.0             Albania            NaN
4  31.0       United States            NaN
5   NaN             Germany            NaN

Bonus Section
Bonus Section So far, we have worked with rows with their index position numbers. We may want to use a column as the index in some scenarios. Let’s convert the Country column to index. Remember that the country column data will now be in the index, and there will be no more Country column in the data frame.

In [21]:
df.set_index('Country', inplace=True)
df

,Age,ConvertedComp,LanguageWorkedWith,YearsCode
Country,,,,
Germany,NaN,NaN,C#;HTML/CSS;JavaScript,36
United Kingdom,NaN,NaN,JavaScript;Swift,7
Russian Federation,NaN,NaN,Objective-C;Python;Swift,4
Albania,25.0,NaN,NaN,7
United States,31.0,NaN,HTML/CSS;Ruby;SQL,15
...,...,...,...,...
United States,NaN,NaN,NaN,10
Morocco,NaN,NaN,Assembly;Bash/Shell/PowerShell;C;C#;C++;Dart;G...,NaN
Viet Nam,NaN,NaN,NaN,NaN
Poland,NaN,NaN,HTML/CSS,NaN
Spain,NaN,NaN,C#;HTML/CSS;Java;JavaScript;SQL,NaN

Now let’s select the data belonging to Morocco and the United States in columns Age to LanguageWorkedWith. Note we are also able to use the range with columns.

In [22]:
df.loc[['Morocco', 'United States'], 'Age':'LanguageWorkedWith']

,Age,ConvertedComp,LanguageWorkedWith
Country,,,
Morocco,26.0,8256.0,Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;SQL
Morocco,28.0,21312.0,C#;HTML/CSS;Java;JavaScript;PHP;R;SQL;TypeScript
Morocco,NaN,NaN,HTML/CSS;JavaScript;Python;SQL
Morocco,21.0,NaN,HTML/CSS;Java;JavaScript;Kotlin;SQL
Morocco,20.0,NaN,C;C#;C++;HTML/CSS;Java;JavaScript;PHP;SQL
...,...,...,...
United States,32.0,NaN,Assembly;Bash/Shell/PowerShell;C;C#;C++;Dart;G...
United States,29.0,NaN,Haskell
United States,NaN,NaN,Bash/Shell/PowerShell;HTML/CSS;PHP
United States,NaN,NaN,C++;HTML/CSS;Java;JavaScript;Python;SQL
United States,NaN,NaN,NaN