In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../survey_results_public.csv')

In [3]:
df

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49118,49119,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,9.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0
49119,49120,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc.)",13.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49120,49121,I am a developer by profession,25-34 years old,"Secondary school (e.g. American high school, G...",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","No, I didn't spend time learning in the past year",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49121,49122,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,None of the above;Engaged in paid work (20-29 ...,10.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0
49122,49123,I am a developer by profession,25-34 years old,Some college/university study without earning ...,Employed,None of the above,10.0,"No, I am not new to coding and did not learn n...",NaN,"No, I learned something that was not related t...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0

View all columns in a data set
Set Option method

As observed in the above output, it does not show all the columns. The default (20 columns) behavior shows a truncated view of the columns and rows. Often we want to get a glance at all the columns and their data. To achieve this, we can use the pd.set_option() method with its option — display.max_columns.

In [8]:
pd.set_option('display.max_columns',61)
df

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,...,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,...,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,...,NaN,NaN,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,12.0,"Developer, front-end",NaN,NaN,NaN,No,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,4.0,14.0,NaN,8.0,...,Learning about a codebase;Writing code;Generat...,NaN,"AI solutions that are almost right, but not qu...",No,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Multi-platform search enablement,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,AI agents have improved collaboration within m...,NaN,NaN,It takes significant time and effort to learn ...,My company's IT and/or InfoSec teams have stri...,NaN,I am concerned about the accuracy of the infor...,NaN,Redis,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,5.0,"Developer, back-end","10,000 or more employees",Individual contributor,Remote,No,Personal Project,2.0,12.0,6.0,5.0,13.0,3.0,8.0,11.0,7.0,14.0,NaN,10.0,...,Search for answers;Generating content or synth...,NaN,"AI solutions that are almost right, but not qu...",NO,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,Language processing,AI agents have accelerated my learning about n...,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,22.0,Engineering manager,NaN,NaN,NaN,"Yes, I endorsed a tool that was open-source an...",Work,6.0,3.0,1.0,9.0,10.0,8.0,7.0,4.0,2.0,14.0,NaN,7.0,...,NaN,NaN,"AI solutions that are almost right, but not quite",partly,"No, and I don't plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,It takes significant time and effort to learn ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49118,49119,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,9.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps;Technical ...,13.0,"Developer, full-stack",500 to 999 employees,Individual contributor,"Hybrid (some remote, leans heavy to in-person)",No,Personal Project,8.0,2.0,4.0,5.0,6.0,7.0,9.0,3.0,1.0,10.0,NaN,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0
49119,49120,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc.)",13.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps;Videos (no...,15.0,"Developer, full-stack","1,000 to 4,999 employees",Individual contributor,"Hybrid (some remote, leans heavy to in-person)","Yes, I endorsed a tool that was open-source an...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49120,49121,I am a developer by profession,25-34 years old,"Secondary school (e.g. American high school, G...",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","No, I didn't spend time learning in the past year",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49121,49122,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,None of the above;Engaged in paid work (20-29 ...,10.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Videos (not associated with specific online co...,14.0,"Developer, full-stack",20 to 99 employees,Individual contributor,"Hybrid (some remote, leans heavy to in-person)","Yes, I influenced the purchase of a substantia...",Work,5.0,6.0,3.0,8.0,1.0,9.0,7.0,4.0,2.0,10.0,NaN,9.0,...,NaN,Learning about a codebase;Search for answers;L...,"AI solutions that are almost right, but not qu...","no, IA do not control de code part, it's essen...","No, I use AI exclusively in copilot/autocomple...",Not at all or minimally,Marketing,Multi-platform search enablement;Language proc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0
49122,49123,I am a developer by profession,25-34 years old,Some college/university study without earning ...,Employed,None of the above,10.0,"No, I am not new to coding and did not learn n...",NaN,"No, I learned something that was not related t...",NaN,15.0,"Developer, full-stack",Less than 20 employees,Individual contributor,"Your choice (very flexible, you can come in wh...","Yes, I influenced the purchase of a substantia...",Personal Project,9.0,2.0,3.0,1.0,6.0,4.0,7.0,5.0,8.0,10.0,NaN,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0

Quick view of the first and the last few rows
Head and tail methods

The head() method returns the first five while the tail() function returns the last five rows of the data set by default. If you like to see more or fewer rows, you can specify any number between brackets ().

In [9]:
df.head(3)

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,...,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,...,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,...,NaN,NaN,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,12.0,"Developer, front-end",NaN,NaN,NaN,No,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,4.0,14.0,NaN,8.0,...,Learning about a codebase;Writing code;Generat...,NaN,"AI solutions that are almost right, but not qu...",No,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Multi-platform search enablement,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,AI agents have improved collaboration within m...,NaN,NaN,It takes significant time and effort to learn ...,My company's IT and/or InfoSec teams have stri...,NaN,I am concerned about the accuracy of the infor...,NaN,Redis,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0

In [10]:
df.tail()

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,...,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
49118,49119,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,9.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps;Technical ...,13.0,"Developer, full-stack",500 to 999 employees,Individual contributor,"Hybrid (some remote, leans heavy to in-person)",No,Personal Project,8.0,2.0,4.0,5.0,6.0,7.0,9.0,3.0,1.0,10.0,NaN,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0
49119,49120,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc.)",13.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps;Videos (no...,15.0,"Developer, full-stack","1,000 to 4,999 employees",Individual contributor,"Hybrid (some remote, leans heavy to in-person)","Yes, I endorsed a tool that was open-source an...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49120,49121,I am a developer by profession,25-34 years old,"Secondary school (e.g. American high school, G...",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","No, I didn't spend time learning in the past year",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49121,49122,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,None of the above;Engaged in paid work (20-29 ...,10.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Videos (not associated with specific online co...,14.0,"Developer, full-stack",20 to 99 employees,Individual contributor,"Hybrid (some remote, leans heavy to in-person)","Yes, I influenced the purchase of a substantia...",Work,5.0,6.0,3.0,8.0,1.0,9.0,7.0,4.0,2.0,10.0,NaN,9.0,...,NaN,Learning about a codebase;Search for answers;L...,"AI solutions that are almost right, but not qu...","no, IA do not control de code part, it's essen...","No, I use AI exclusively in copilot/autocomple...",Not at all or minimally,Marketing,Multi-platform search enablement;Language proc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0
49122,49123,I am a developer by profession,25-34 years old,Some college/university study without earning ...,Employed,None of the above,10.0,"No, I am not new to coding and did not learn n...",NaN,"No, I learned something that was not related t...",NaN,15.0,"Developer, full-stack",Less than 20 employees,Individual contributor,"Your choice (very flexible, you can come in wh...","Yes, I influenced the purchase of a substantia...",Personal Project,9.0,2.0,3.0,1.0,6.0,4.0,7.0,5.0,8.0,10.0,NaN,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0

Summary of the data set size and its elements
Shape attribute
shape() is a data frame attribute that returns the size of the data set with the total number of rows and the number of columns (rows, columns) in the data set.

In [11]:
df.shape

(49123, 170)

Info method

The info() method shows a concise summary of the data frame as the name indicates. It returns the data frame Index, the total number of rows & columns, columns names, column data types, non-null values and count of different data types.

Non-null values are essential to note here. They show much data is in each column is use able. Null values are not that useful, and you might want to replace them with some data or remove those rows altogether. We will review data cleaning techniques in a future article.

In [14]:
df.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49123 entries, 0 to 49122
Data columns (total 170 columns):
 #    Column                                    Non-Null Count  Dtype
---   ------                                    --------------  -----
 0    ResponseId                                49123 non-null  int64
 1    MainBranch                                49123 non-null  object
 2    Age                                       49123 non-null  object
 3    EdLevel                                   48087 non-null  object
 4    Employment                                48277 non-null  object
 5    EmploymentAddl                            44820 non-null  object
 6    WorkExp                                   42844 non-null  float64
 7    LearnCodeChoose                           46801 non-null  object
 8    LearnCode                                 33516 non-null  object
 9    LearnCodeAI                               45153 non-null  object
 10   AILearnHow                                28224 non-null  object
 11   YearsCode                                 43000 non-null  float64
 12   DevType                                   43636 non-null  object
 13   OrgSize                                   34144 non-null  object
 14   ICorPM                                    33211 non-null  object
 15   RemoteWork                                33747 non-null  object
 16   PurchaseInfluence                         37402 non-null  object
 17   TechEndorseIntro                          37520 non-null  object
 18   TechEndorse_1                             35943 non-null  float64
 19   TechEndorse_2                             35943 non-null  float64
 20   TechEndorse_3                             35943 non-null  float64
 21   TechEndorse_4                             35943 non-null  float64
 22   TechEndorse_5                             35943 non-null  float64
 23   TechEndorse_6                             35943 non-null  float64
 24   TechEndorse_7                             35943 non-null  float64
 25   TechEndorse_8                             35943 non-null  float64
 26   TechEndorse_9                             35943 non-null  float64
 27   TechEndorse_13                            35943 non-null  float64
 28   TechEndorse_13_TEXT                       2008 non-null   object
 29   TechOppose_1                              34227 non-null  float64
 30   TechOppose_2                              34227 non-null  float64
 31   TechOppose_3                              34227 non-null  float64
 32   TechOppose_5                              34227 non-null  float64
 33   TechOppose_7                              34227 non-null  float64
 34   TechOppose_9                              34227 non-null  float64
 35   TechOppose_11                             34227 non-null  float64
 36   TechOppose_13                             34227 non-null  float64
 37   TechOppose_16                             34227 non-null  float64
 38   TechOppose_15                             34227 non-null  float64
 39   TechOppose_15_TEXT                        1645 non-null   object
 40   Industry                                  33607 non-null  object
 41   JobSatPoints_1                            24917 non-null  float64
 42   JobSatPoints_4                            24917 non-null  float64
 43   JobSatPoints_5                            24917 non-null  float64
 44   JobSatPoints_6                            24917 non-null  float64
 45   JobSatPoints_7                            24917 non-null  float64
 46   JobSatPoints_8                            24917 non-null  float64
 47   JobSatPoints_9                            24917 non-null  float64
 48   JobSatPoints_10                           24917 non-null  float64
 49   JobSatPoints_11                           24917 non-null  float64
 50   JobSatPoints_13                           24917 non-null  float64
 51   JobSatPoints_14                           24917 non-null  float64
 52   JobSatPoints_15                           24917 non-null  float64
 53   JobSatPoints_16                           24917 non-null  float64
 54   JobSatPoints_15_TEXT                      664 non-null    object
 55   AIThreat                                  36041 non-null  object
 56   NewRole                                   35491 non-null  object
 57   ToolCountWork                             27582 non-null  float64
 58   ToolCountPersonal                         25555 non-null  float64
 59   Country                                   35402 non-null  object
 60   Currency                                  35402 non-null  object
 61   CompTotal                                 24839 non-null  float64
 62   LanguageChoice                            32185 non-null  object
 63   LanguageHaveWorkedWith                    31643 non-null  object
 64   LanguageWantToWorkWith                    27054 non-null  object
 65   LanguageAdmired                           23447 non-null  object
 66   LanguagesHaveEntry                        3975 non-null   object
 67   LanguagesWantEntry                        3145 non-null   object
 68   DatabaseChoice                            31659 non-null  object
 69   DatabaseHaveWorkedWith                    25528 non-null  object
 70   DatabaseWantToWorkWith                    19718 non-null  object
 71   DatabaseAdmired                           17282 non-null  object
 72   DatabaseHaveEntry                         2148 non-null   object
 73   DatabaseWantEntry                         1528 non-null   object
 74   PlatformChoice                            31233 non-null  object
 75   PlatformHaveWorkedWith                    24234 non-null  object
 76   PlatformWantToWorkWith                    19396 non-null  object
 77   PlatformAdmired                           17804 non-null  object
 78   PlatformHaveEntry                         3952 non-null   object
 79   PlatformWantEntry                         3096 non-null   object
 80   WebframeChoice                            31164 non-null  object
 81   WebframeHaveWorkedWith                    22970 non-null  object
 82   WebframeWantToWorkWith                    17623 non-null  object
 83   WebframeAdmired                           15697 non-null  object
 84   WebframeHaveEntry                         3290 non-null   object
 85   WebframeWantEntry                         2626 non-null   object
 86   DevEnvsChoice                             31051 non-null  object
 87   DevEnvsHaveWorkedWith                     25994 non-null  object
 88   DevEnvsWantToWorkWith                     20592 non-null  object
 89   DevEnvsAdmired                            19470 non-null  object
 90   DevEnvHaveEntry                           2760 non-null   object
 91   DevEnvWantEntry                           2110 non-null   object
 92   SOTagsHaveWorkedWith                      17906 non-null  object
 93   SOTagsWantToWorkWith                      13576 non-null  object
 94   SOTagsAdmired                             12229 non-null  object
 95   SOTagsHaveEntry                           457 non-null    object
 96   SOTagsWant Entry                          430 non-null    object
 97   OpSysPersonal use                         31388 non-null  object
 98   OpSysProfessional use                     28858 non-null  object
 99   OfficeStackAsyncHaveWorkedWith            29830 non-null  object
 100  OfficeStackAsyncWantToWorkWith            23183 non-null  object
 101  OfficeStackAsyncAdmired                   22185 non-null  object
 102  OfficeStackHaveEntry                      2587 non-null   object
 103  OfficeStackWantEntry                      1617 non-null   object
 104  CommPlatformHaveWorkedWith                30038 non-null  object
 105  CommPlatformWantToWorkWith                23330 non-null  object
 106  CommPlatformAdmired                       22856 non-null  object
 107  CommPlatformHaveEntr                      1475 non-null   object
 108  CommPlatformWantEntr                      1183 non-null   object
 109  AIModelsChoice                            30210 non-null  object
 110  AIModelsHaveWorkedWith                    16261 non-null  object
 111  AIModelsWantToWorkWith                    11832 non-null  object
 112  AIModelsAdmired                           11272 non-null  object
 113  AIModelsHaveEntry                         775 non-null    object
 114  AIModelsWantEntry                         474 non-null    object
 115  SOAccount                                 32767 non-null  object
 116  SOVisitFreq                               32680 non-null  object
 117  SODuration                                32597 non-null  object
 118  SOPartFreq                                32200 non-null  object
 119  SO_Dev_Content                            22820 non-null  object
 120  SO_Actions_1                              26241 non-null  float64
 121  SO_Actions_16                             24321 non-null  float64
 122  SO_Actions_3                              26241 non-null  float64
 123  SO_Actions_4                              26241 non-null  float64
 124  SO_Actions_5                              26241 non-null  float64
 125  SO_Actions_6                              26241 non-null  float64
 126  SO_Actions_9                              26241 non-null  float64
 127  SO_Actions_7                              26241 non-null  float64
 128  SO_Actions_10                             26241 non-null  float64
 129  SO_Actions_15                             26241 non-null  float64
 130  SO_Actions_15_TEXT                        823 non-null    object
 131  SOComm                                    31678 non-null  object
 132  SOFriction                                30763 non-null  object
 133  AISelect                                  33686 non-null  object
 134  AISent                                    33434 non-null  object
 135  AIAcc                                     33264 non-null  object
 136  AIComplex                                 33250 non-null  object
 137  AIToolCurrently partially AI              21003 non-null  object
 138  AIToolDon't plan to use AI for this task  25358 non-null  object
 139  AIToolPlan to partially use AI            22531 non-null  object
 140  AIToolPlan to mostly use AI               12801 non-null  object
 141  AIToolCurrently mostly AI                 11210 non-null  object
 142  AIFrustration                             31491 non-null  object
 143  AIExplain                                 26564 non-null  object
 144  AIAgents                                  31890 non-null  object
 145  AIAgentChange                             31647 non-null  object
 146  AIAgent_Uses                              12307 non-null  object
 147  AgentUsesGeneral                          5800 non-null   object
 148  AIAgentImpactSomewhat agree               10135 non-null  object
 149  AIAgentImpactNeutral                      9665 non-null   object
 150  AIAgentImpactSomewhat disagree            5784 non-null   object
 151  AIAgentImpactStrongly agree               6682 non-null   object
 152  AIAgentImpactStrongly disagree            3776 non-null   object
 153  AIAgentChallengesNeutral                  21279 non-null  object
 154  AIAgentChallengesSomewhat disagree        12116 non-null  object
 155  AIAgentChallengesStrongly agree           23082 non-null  object
 156  AIAgentChallengesSomewhat agree           21927 non-null  object
 157  AIAgentChallengesStrongly disagree        9305 non-null   object
 158  AIAgentKnowledge                          3400 non-null   object
 159  AIAgentKnowWrite                          765 non-null    object
 160  AIAgentOrchestration                      3760 non-null   object
 161  AIAgentOrchWrite                          477 non-null    object
 162  AIAgentObserveSecure                      2691 non-null   object
 163  AIAgentObsWrite                           264 non-null    object
 164  AIAgentExternal                           8326 non-null   object
 165  AIAgentExtWrite                           858 non-null    object
 166  AIHuman                                   29167 non-null  object
 167  AIOpen                                    22520 non-null  object
 168  ConvertedCompYearly                       23928 non-null  float64
 169  JobSat                                    26643 non-null  float64
dtypes: float64(50), int64(1), object(119)
memory usage: 63.7+ MB

Descriptive statistics summary
Describe method

The describe() method is used to see the summary of the descriptive statistics. It summarizes a data set and shows the output with central tendency (mean), dispersion (standard deviation), percentile (25th, 50th, 75th), count, min and max.

In [ ]:
df.describe()

,ResponseId,WorkExp,YearsCode,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,ToolCountWork,ToolCountPersonal,CompTotal,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,ConvertedCompYearly,JobSat
count,49123.000000,42844.000000,43000.000000,35943.000000,35943.000000,35943.000000,35943.000000,35943.000000,35943.000000,35943.000000,35943.000000,35943.000000,35943.000000,34227.000000,34227.000000,34227.000000,34227.000000,34227.000000,34227.000000,34227.000000,34227.000000,34227.000000,34227.000000,24917.000000,24917.000000,24917.000000,24917.000000,24917.000000,24917.000000,24917.000000,24917.000000,24917.000000,24917.000000,24917.000000,24917.000000,24917.000000,27582.000000,25555.000000,2.483900e+04,26241.000000,24321.000000,26241.000000,26241.000000,26241.000000,26241.000000,26241.000000,26241.000000,26241.000000,26241.000000,2.392800e+04,26643.000000
mean,24562.000000,13.370810,16.575256,7.867763,4.104415,4.110341,5.678574,4.119383,5.225830,6.477562,4.370921,4.431656,9.854269,8.308558,4.524031,5.925965,4.992608,4.049084,3.799369,4.365238,5.059719,5.508254,9.946154,6.868042,9.539190,9.758839,8.196131,5.884135,7.365774,6.745154,7.513264,5.702091,8.563150,8.679656,14.687161,7.826103,17.745015,8.547368,2.236626e+70,4.908731,3.340035,5.718456,4.562097,4.791014,5.198925,5.676232,4.984033,7.100149,10.079341,1.017916e+05,7.202042
std,14180.732974,10.801917,11.789269,2.397243,2.276154,2.329539,2.397899,2.437938,2.801354,2.331433,2.357171,2.621219,1.976538,2.202392,2.282783,2.301720,2.294630,2.607674,2.499572,2.557246,2.533801,2.906259,2.087658,3.741658,3.780484,3.556890,3.801592,3.900073,4.118598,3.888805,3.847620,4.110147,3.544728,3.633036,1.899151,4.078090,269.951701,44.687664,3.525011e+72,2.682176,2.411611,2.628090,3.070817,2.643243,2.563386,2.311023,2.490411,2.469361,1.941629,4.619345e+05,1.997234
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000e+00,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000e+00,0.000000
25%,12281.500000,5.000000,8.000000,7.000000,2.000000,2.000000,4.000000,2.000000,3.000000,5.000000,2.000000,2.000000,10.000000,8.000000,3.000000,4.000000,3.000000,2.000000,2.000000,2.000000,3.000000,3.000000,10.000000,4.000000,7.000000,7.000000,5.000000,2.000000,4.000000,3.000000,4.000000,2.000000,6.000000,6.000000,15.000000,4.000000,4.000000,3.000000,5.500000e+04,3.000000,1.000000,3.000000,1.000000,3.000000,3.000000,4.000000,3.000000,6.000000,10.000000,3.817100e+04,6.000000
50%,24562.000000,10.000000,14.000000,9.000000,4.000000,4.000000,6.000000,4.000000,5.000000,7.000000,4.000000,4.000000,10.000000,9.000000,4.000000,6.000000,5.000000,4.000000,3.000000,4.000000,5.000000,6.000000,10.000000,6.000000,10.000000,10.000000,8.000000,5.000000,7.000000,6.000000,7.000000,5.000000,9.000000,9.000000,15.000000,8.000000,6.000000,5.000000,1.050000e+05,5.000000,2.000000,6.000000,4.000000,5.000000,5.000000,6.000000,5.000000,8.000000,10.000000,7.538350e+04,8.000000
75%,36842.500000,20.000000,24.000000,9.000000,6.000000,6.000000,8.000000,6.000000,8.000000,8.000000,6.000000,7.000000,10.000000,9.000000,6.000000,8.000000,7.000000,6.000000,6.000000,6.000000,7.000000,8.000000,10.000000,10.000000,13.000000,13.000000,11.000000,9.000000,11.000000,10.000000,11.000000,9.000000,12.000000,12.000000,15.000000,11.000000,10.000000,7.000000,2.400000e+05,7.000000,5.000000,8.000000,7.000000,7.000000,7.000000,7.000000,7.000000,9.000000,10.000000,1.206302e+05,8.000000
max,49123.000000,100.000000,100.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,14.000000,15.000000,15.000000,16.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,10000.000000,1000.000000,5.555556e+74,15.000000,10.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,5.000000e+07,10.000000

Random data sampling
Sample method

The sample() method returns a random number of rows and columns from the data frame. By default, it returns one row, but we can input any number in the method brackets.

In [15]:
df.sample()

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,...,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
32436,32437,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,Attending school (part-time),10.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",Videos (not associated with specific online co...,15.0,"Architect, software or solutions",100 to 499 employees,Individual contributor,"Your choice (very flexible, you can come in wh...",No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df.sample(3)

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,...,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
38207,38208,"I am not primarily a developer, but I write co...",55-64 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,35.0,"No, I am not new to coding and did not learn n...",NaN,"No, I learned something that was not related t...",NaN,45.0,System administrator,"1,000 to 4,999 employees",Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,10.0,7.0,8.0,4.0,5.0,1.0,2.0,3.0,6.0,9.0,NaN,9.0,...,NaN,NaN,I don’t use AI tools regularly,NaN,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I need qu...,NaN,52207.0,NaN
28885,28886,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,16.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","No, I didn't spend time learning in the past year",NaN,25.0,"Architect, software or solutions",20 to 99 employees,Individual contributor,"Hybrid (some remote, leans heavy to in-person)",No,Work,9.0,7.0,3.0,8.0,2.0,1.0,4.0,5.0,6.0,10.0,NaN,9.0,...,Documenting code,NaN,"AI solutions that are almost right, but not qu...",No,"No, I use AI exclusively in copilot/autocomple...",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,AI agents have increased my productivity.;AI a...,NaN,NaN,I am concerned about the accuracy of the infor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I’m stuck and can’t explain the problem,"How to read code, understanding time and space...",63808.0,7.0
43971,43972,I am a developer by profession,25-34 years old,Other (please specify):,Employed,Engaged in paid work (less than 10 hours per w...,11.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","No, I learned something that was not related t...",NaN,13.0,"Developer, full-stack","1,000 to 4,999 employees",Individual contributor,"Hybrid (some remote, leans heavy to in-person)",No,Work,8.0,5.0,3.0,4.0,6.0,9.0,7.0,1.0,2.0,10.0,NaN,9.0,...,Testing code,NaN,Debugging AI-generated code is more time-consu...,No,"No, but I plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,NaN,57079.0,NaN

Unique values and frequency tables
Unique method

The unique() method returns a unique value of a column. Null values are excluded by default.

In [18]:
df.AILearnHow.unique()

array(['AI CodeGen tools or AI-enabled apps',
       'AI CodeGen tools or AI-enabled apps;Technical documentation (is generated for/by the tool or system);Videos (not associated with specific online course or certification)',
       'AI CodeGen tools or AI-enabled apps;Videos (not associated with specific online course or certification);Other online resources (e.g. standard search, forum, online community)',
       ...,
       'AI CodeGen tools or AI-enabled apps;Technical documentation (is generated for/by the tool or system);Videos (not associated with specific online course or certification);Coding Bootcamp;School (i.e., University, College, etc)',
       'AI CodeGen tools or AI-enabled apps;Technical documentation (is generated for/by the tool or system);Online Courses or Certification (includes all media types);Books / Physical media;School (i.e., University, College, etc)',
       'AI CodeGen tools or AI-enabled apps;Other online resources (e.g. standard search, forum, online community);Colleague or on-the-job training;Stack Overflow or Stack Exchange;Games or coding challenges;Books / Physical media'],
      shape=(1675,), dtype=object)

Value counts method

value_counts() method takes things a step further. It shows unique values in a column as well as their count. The output is a concise and useful frequency table in descending order.

In [20]:
df.Age.value_counts()

Age
25-34 years old      16485
35-44 years old      13232
18-24 years old       9195
45-54 years old       6265
55-64 years old       2626
65 years or older      942
Prefer not to say      378
Name: count, dtype: int64

Correlation between columns

In statistics, correlation shows the relationship between two numerical variables (columns in our case). This method helps us quickly review if any two columns have a negative or positive correlation (values are between 0 and 1).

A value of one means the two variables are positively correlated, and an increase in one variable results in an increase in the other variable and vice versa. In the output below, we can see that the correlation between ConvertedComp and Age columns is positive and weak (0.107002).

It excludes null values and object data types columns by default. It is an essential method while making a feature selection for the machine learning model (more on this later)

In [22]:
df.corr(numeric_only=True)

,ResponseId,WorkExp,YearsCode,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,ToolCountWork,ToolCountPersonal,CompTotal,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,ConvertedCompYearly,JobSat
ResponseId,1.000000,-0.042428,-0.075291,-0.203424,-0.020527,-0.013801,-0.083397,-0.029393,-0.044400,-0.105478,-0.052431,-0.038318,-0.190032,-0.241848,-0.049587,-0.067011,-0.085956,-0.029710,-0.040402,-0.022811,-0.066118,-0.104670,-0.215975,0.108679,-0.015436,-0.005071,-0.018042,-0.006626,-0.022493,-0.031914,-0.042555,-0.001402,-0.059533,-0.080407,0.008695,0.058332,0.005409,0.009398,-0.007771,-0.094863,0.029142,-0.118210,-0.024946,-0.068386,-0.018949,-0.066523,-0.041101,-0.180778,-0.240668,0.004284,-0.001012
WorkExp,-0.042428,1.000000,0.836966,-0.011070,0.028013,0.010455,0.018660,-0.000876,0.049487,0.022552,0.006983,-0.016802,-0.023491,-0.001409,0.048752,0.037641,0.026139,-0.055858,-0.007923,0.018162,0.048566,-0.012467,0.024517,-0.081705,0.193396,-0.046230,0.030895,-0.053057,0.057389,-0.063854,-0.009494,0.030898,0.014754,0.015468,-0.029113,0.014112,0.054826,0.082002,0.053595,0.024068,0.057383,0.051764,0.044851,-0.034900,-0.094140,-0.032773,0.044827,0.019807,0.026486,0.054091,0.105810
YearsCode,-0.075291,0.836966,1.000000,0.084300,0.007033,-0.036761,0.037840,-0.026514,0.043216,0.051680,-0.011847,-0.022957,-0.031977,0.088514,0.049786,0.027236,0.033470,-0.062047,-0.035770,-0.008124,0.060591,-0.015574,0.009189,-0.095384,0.220975,-0.031048,0.044733,-0.049423,0.060427,-0.076135,0.013133,0.022734,0.004061,0.023473,-0.041949,-0.000396,0.047317,0.061273,0.046362,0.042503,0.011457,0.075908,0.020173,-0.010906,-0.098890,-0.033230,0.002720,0.082917,0.017946,0.057760,0.094128
TechEndorse_1,-0.203424,-0.011070,0.084300,1.000000,-0.062120,-0.135318,0.037406,-0.130772,-0.094029,0.090103,-0.087815,-0.044235,0.009785,0.588591,0.027435,0.056388,0.077489,-0.041267,-0.086919,-0.079082,0.102664,0.024244,0.047022,-0.136353,0.075380,0.087070,0.045040,-0.016082,0.003773,-0.000511,0.126015,-0.014028,0.039312,0.089464,-0.061748,-0.065896,-0.001117,0.003620,-0.000034,0.063929,-0.127089,0.086567,-0.046482,0.066431,0.052935,0.065814,0.014688,0.272756,0.129314,-0.004602,-0.031432
TechEndorse_2,-0.020527,0.028013,0.007033,-0.062120,1.000000,0.154896,-0.093300,-0.152181,-0.132118,-0.150966,-0.118716,-0.096124,-0.032802,-0.027333,0.134482,0.151678,0.015654,0.004384,-0.050880,0.022277,0.035424,-0.059189,0.005920,-0.021587,-0.013629,-0.016877,-0.040789,-0.004786,0.027722,-0.031066,0.014384,0.052534,0.010861,0.011865,-0.021203,0.002685,0.014792,0.022496,0.008607,0.022455,0.018769,-0.000367,0.001332,0.033981,0.010028,0.002925,0.032595,0.007702,0.030034,0.001166,0.025654
TechEndorse_3,-0.013801,0.010455,-0.036761,-0.135318,0.154896,1.000000,-0.052977,-0.127405,-0.133026,-0.204004,-0.001049,-0.145915,-0.004725,-0.084670,0.040270,0.192797,0.001005,-0.048924,0.049984,0.055537,0.051058,-0.029874,0.046233,0.004276,-0.037317,-0.032881,-0.006197,0.018428,0.000336,0.042675,0.007814,0.022742,0.014001,-0.006746,-0.016015,-0.041380,0.013738,0.013840,0.005545,0.020235,0.048982,0.020489,0.028174,0.000215,0.021796,0.015234,0.026922,-0.011389,0.055862,0.001050,0.003192
TechEndorse_4,-0.083397,0.018660,0.037840,0.037406,-0.093300,-0.052977,1.000000,-0.174137,-0.006913,-0.126049,-0.051241,-0.148519,0.035547,0.114037,0.053474,0.052471,0.056981,-0.058398,0.007389,0.005418,0.057181,0.042094,0.094871,-0.038549,0.022260,0.023742,0.060531,-0.000982,0.010960,0.047693,0.036575,-0.051687,0.016537,0.027437,-0.016610,-0.077272,-0.007001,-0.011791,-0.007566,0.045542,-0.038586,0.066369,-0.009923,0.015541,0.046617,0.038089,-0.005274,0.096492,0.105982,0.006397,0.014859
TechEndorse_5,-0.029393,-0.000876,-0.026514,-0.130772,-0.152181,-0.127405,-0.174137,1.000000,-0.116109,0.076762,-0.026346,-0.095245,-0.005662,-0.066463,0.036340,-0.059332,0.016804,-0.006976,0.089271,0.073893,0.056450,0.045524,0.049725,-0.001250,-0.034055,-0.046937,-0.041809,0.004928,0.016824,0.017727,-0.019960,0.040341,0.024523,0.020180,-0.013748,0.000275,-0.000075,0.005736,0.016044,0.026073,0.037350,0.032935,0.027874,0.014710,-0.005019,0.006107,0.036689,-0.016542,0.064354,-0.005449,-0.003108
TechEndorse_6,-0.044400,0.049487,0.043216,-0.094029,-0.132118,-0.133026,-0.006913,-0.116109,1.000000,-0.072268,-0.169860,-0.175995,0.065182,0.010162,-0.035575,0.003180,-0.047431,0.015647,0.038002,0.024911,0.016107,0.156545,0.148081,0.009587,0.007423,0.012748,0.034667,0.027359,-0.045307,0.027376,0.021230,-0.055474,0.041673,0.011710,0.006122,-0.043197,0.004292,-0.021373,-0.000710,0.028019,-0.004009,0.042588,0.021216,-0.007886,0.026562,0.035054,0.028854,0.023265,0.104248,0.013032,0.017158
TechEndorse_7,-0.105478,0.022552,0.051680,0.090103,-0.150966,-0.204004,-0.126049,0.076762,-0.072268,1.000000,-0.136753,-0.073947,0.023574,0.186696,0.006272,0.007031,0.009267,-0.006422,-0.009660,-0.004843,0.057462,0.101221,0.090264,-0.062147,0.016053,0.010528,-0.001854,-0.024115,0.027830,-0.026012,0.022693,-0.003219,0.055502,0.084227,-0.026949,0.017504,-0.000294,-0.002312,-0.012894,0.042625,-0.037887,0.054277,-0.007182,0.020617,0.002772,0.063211,0.046668,0.125780,0.119581,0.006165,-0.002198
TechEndorse_8,-0.052431,0.006983,-0.011847,-0.087815,-0.118716,-0.001049,-0.051241,-0.026346,-0.169860,-0.136753,1.000000,-0.055630,0.011346,-0.043615,0.039408,0.004320,0.118877,-0.032349,0.118787,0.053088,-0.004185,0.012222,0.053377,-0.007851,-0.033008,-0.038826,-0.005010,0.019768,0.012475,0.059406,-0.005148,0.041233,-0.001776,-0.000577,-0.023911,-0.031153,0.006279,0.002644,0.012949,0.036766,0.037268,0.028542,0.034543,0.000745,0.016266,0.012346,0.015954,0.011077,0.078398,-0.019113,-0.014068
TechEndorse_9,-0.038318,-0.016802,-0.022957,-0.044235,-0.096124,-0.145915,-0.148519,-0.095245,-0.175995,-0.073947,-0.055630,1.000000,0.012588,-0.013491,-0.044428,-0.064574,0.071862,0.318367,0.022819,0.027563,-0.061146,-0.034832,0.021834,-0.048985,-0.038116,-0.050837,-0.038218,0.000577,0.034937,0.004524,-0.021204,0.083690,0.004990,0.017038,0.017114,0.038446,0.007691,0.014857,-0.000853,0.007823,0.041865,0.007085,0.030524,0.022372,-0.009415,0.008444,0.044707,0.007564,0.067137,0.003757,0.000852
TechEndorse_13,-0.190032,-0.023491,-0.031977,0.009785,-0.032802,-0.004725,0.035547,-0.005662,0.065182,0.023574,0.011346,0.012588,1.000000,0.101856,0.038707,0.040992,0.056242,0.035272,0.075104,0.052090,0.012179,0.153810,0.587550,-0.072672,-0.059627,-0.036239,-0.007417,0.015624,0.004134,0.066632,-0.000231,-0.002762,0.061677,0.061691,0.176736,-0.029305,-0.059838,-0.044483,-0.028563,0.059116,0.011493,0.089714,0.065486,0.037647,0.049579,0.077986,0.071632,0.121444,0.406069,-0.001127,0.009905
TechOppose_1,-0.241848,-0.001409,0.088514,0.588591,-0.027333,-0.084670,0.114037,-0.066463,0.010162,0.186696,-0.043615,-0.013491,0.101856,1.000000,0.002212,0.065659,0.046437,-0.071521,-0.137224,-0.102376,0.069134,0.019995,0.099333,-0.143016,0.089583,0.087862,0.053367,-0.024286,0.012757,-0.005157,0.114956,-0.030161,0.063228,0.113623,-0.053817,-0.069084,0.002815,0.002697,-0.001424,0.082865,-0.157270,0.120959,-0.038873,0.074663,0.068144,0.102058,0.033578,0.329014,0.214391,-0.002807,-0.019005
TechOppose_2,-0.049587,0.048752,0.049786,0.027435,0.134482,0.040270,0.053474,0.036340,-0.035575,0.006272,0.039408,-0.044428,0.038707,0.002212,1.000000,0.004876,0.009513,-0.108847,-0.158498,-0.083729,-0.051716,-0.154826,0.010329,-0.030854,0.001414,-0.011316,0.007162,-0.005793,0.017929,0.008301,0.012222,0.017581,0.039096,0.030324,-0.016834,-0.033655,-0.000471,0.003281,0.001448,0.035572,0.006021,0.026087,0.000908,0.031670,0.009988,0.025176,0.013636,0.048120,0.058597,0.015234,0.029416
TechOppose_3,-0.067011,0.037641,0.027236,0.056388,0.151678,0.192797,0.052471,-0.059332,0.003180,0.007031,0.004320,-0.064574,0.040992,0.065659,0.004876,1.000000,-0.061364,-0.109540,-0.130115,-0.067436,-0.061278,-0.128700,0.056855,-0.022810,0.011555,0.002469,0.011804,-0.014269,0.003156,0.024691,0.004481,0.008136,0.016328,0.020941,-0.019980,-0.002006,0.004143,-0.002054,-0.005567,0.029444,-0.022654,0.037996,0.010626,0.015563,0.035831,0.042523,0.032844,0.072460,0.093356,-0.019692,0.003488
TechOppose_5,-0.085956,0.026139,0.033470,0.077489,0.015654,0.001005,0.056981,0.016804,-0.047431,0.009267,0.118877,0.071862,0.056242,0.046437,0.009513,-0.061364,1.000000,-0.027557,-0.103622,-0.075398,-0.063735,-0.153236,0.021532,-0.047272,-0.004998,-0.021993,0.012790,0.013315,0.008444,0.036281,0.019624,0.031648,0.027157,0.033635,-0.025367,-0.051369,-0.004553,0.004054,0.011643,0.047410,-0.004112,0.038744,0.003120,0.021090,0.024537,0.028975,0.039897,0.064647,0.098657,0.008022,0.004349
TechOppose_7,-0.029710,-0.055858,-0.062047,-0.041267,0.004384,-0.048924,-0.058398,-0.006976,0.015647,-0.006422,-0.032349,0.318367,0.035272,-0.071521,-0.108847,-0.109540,-0.027557,1.000000,-0.115425,-0.047730,-0.137689,-0.133801,0.012856,-0.030258,-0.052110,-0.051118,-0.022641,0.001225,0.025319,0.016548,-0.000570,0.069673,0.005608,0.030423,0.004445,0.016978,0.022020,0.016225,0.005022,0.020455,0.032105,0.014199,0.032115,0.016697,-0.012743,0.001092,0.038122,-0.007275,0.066965,0.005825,0.004693
TechOppose_9,-0.040402,-0.007923,-0.035770,-0.086919,-0.050880,0.049984,0.007389,0.089271,0.038002,-0.009660,0.118787,0.022819,0.075104,-0.137224,-0.158498,-0.130115,-0.103622,-0.115425,1.000000,-0.113574,-0.098215,0.119704,0.055511,0.001085,-0.055542,-0.039086,-0.043548,0.033569,0.022076,0.040910,-0.020979,0.020263,0.007843,0.000331,-0.001251,-0.012521,0.002001,0.004928,0.008594,0.034822,0.053114,0.040941,0.043236,-0.006836,0.027082,0.014988,0.015711,-0.030620,0.084557,-0.017142,-0.014562
TechOppose_11,-0.022811,0.018162,-0.008124,-0.079082,0.022277,0.055537,0.005418,0.073893,0.024911,-0.004843,0.053088,0.027563,0.052090,-0.102376,-0.083729,-0.067436,-0.075398,-0.047730,-0.113574,1.000000,-0.062825,-0.166482,0.025608,-0.012018,-0.040248,-0.055928,-0.008166,-0.009596,0.000486,0.031393,-0.006434,0.045128,0.014417,0.010944,0.007849,0.003972,-0.003724,-0.001919,0.014814,0.016460,0.055393,0.006069,0.051791,0.011085,-0.018608,0.005692,0.049416,-0.015992,0.063485,-0.000078,0.017460
TechOppose_13,-0.066118,0.048566,0.060591,0.102664,0.035424,0.051058,0.057181,0.056450,0.016107,0.057462,-0.004185,-0.061146,0.012179,0.069134,-0.051716,-0.061278,-0.063735,-0.137689,-0.098215,-0.062825,1.000000,-0.165198,-0.013698,-0.047110,0.000909,-0.011876,0.017896,-0.006480,0.006489,0.005418,0.159028,0.007742,0.013152,0.048414,-0.057463,-0.084423,0.007932,0.022172,-0.005374,0.041595,-0.003160,0.039610,-0.000138,0.013761,-0.000333,0.029995,0.047177,0.079346,0.052197,0.016299,-0.010826
TechOppose_16,-0.104670,-0.012467,-0.015574,0.024244,-0.059189,-0.029874,0.042094,0.045524,0.156545,0.101221,0.012222,-0.034832,0.153810,0.019995,-0.154826,-0.128700,-0.153236,-0.133801,0.119704,-0.166482,-0.165198,1.000000,0.185452,-0.028001,0.001315,0.041378,-0.023501,0.032510,-0.010550,0.021409,-0.055814,-0.052586,0.058957,0.021905,0.021585,0.007639,-0.003121,-0.018808,-0.008081,0.034960,-0.007973,0.065212,0.025478,0.032032,0.039774,0.046643,0.021976,0.084050,0.184153,-0.005619,0.005421
TechOppose_15,-0.215975,0.024517,0.009189,0.047022,0.005920,0.046233,0.094871,0.049725,0.148081,0.090264,0.053377,0.021834,0.587550,0.099333,0.010329,0.056855,0.021532,0.012856,0.055511,0.025608,-0.013698,0.185452,1.000000,-0.083063,-0.052601,-0.030162,0.002251,0.015446,0.013527,0.066587,-0.000827,0.008340,0.081637,0.063685,0.157974,-0.042476,-0.047994,-0.048062,-0.028142,0.076159,0.006070,0.127822,0.061929,0.037224,0.062107,0.095105,0.093960,0.146763,0.475498,0.001293,0.023674
JobSatPoints_1,0.108679,-0.081705,-0.095384,-0.136353,-0.021587,0.004276,-0.038549,-0.001250,0.009587,-0.062147,-0.007851,-0.048985,-0.072672,-0.143016,-0.030854,-0.022810,-0.047272,-0.030258,0.001085,-0.012018,-0.047110,-0.028001,-0.083063,1.000000,-0.132717,-0.017645,-0.059014,-0.018526,-0.156208,-0.030678,-0.067207,-0.142502,-0.136966,-0.155594,-0.015948,-0.086333,-0.013704,-0.020199,0.009959,-0.042563,0.028795,-0.045924,-0.007104,-0.045038,0.000204,-0.018338,-0.018025,-0.105391,-0.101809,-0.005129,-0.009198
JobSatPoints_4,-0.015436,0.193396,0.220975,0.075380,-0.013629,-0.037317,0.022260,-0.034055,0.007423,0.016053,-0.033008,-0.038116,-0.059627,0.089583,0.001414,0.011555,-0.004998,-0.052110,-0.055542,-0.040248,0.000909,0.001315,-0.052601,-0.132717,1.000000,0.014574,-0.017909,-0.121147,-0.069027,-0.132101,-0.071126,-0.081176,-0.082882,-0.089147,-0.073056,-0.007619,-0.008486,-0.003729,-0.001244,0.001758,-0.045284,0.026067,-0.034964,0.021372,-0.032365,-0.012624,-0.030764,0.063916,-0.040675,0.032129,0.061937
JobSatPoints_5,-0.005071,-0.046230,-0.031048,0.087070,-0.016877,-0.032881,0.023742,-0.046937,0.012748,0.010528,-0.038826,-0.050837,-0.036239,0.087862,-0.011316,0.002469,-0.021993,-0.051118,-0.039086,-0.055928,-0.011876,0.041378,-0.030162,-0.017645,0.014574,1.000000,-0.074175,-0.063764,-0.112632,-0.094822,-0.081002,-0.161642,-0.043521,-0.059365,-0.046925,-0.090713,-0.005454,0.003233,-0.011953,-0.040728,-0.061661,-0.012121,-0.045402,0.007944,0.066320,0.009654,-0.015144,0.039389,-0.039088,-0.010783,0.010592
JobSatPoints_6,-0.018042,0.030895,0.044733,0.045040,-0.040789,-0.006197,0.060531,-0.041809,0.034667,-0.001854,-0.005010,-0.038218,-0.007417,0.053367,0.007162,0.011804,0.012790,-0.022641,-0.043548,-0.008166,0.017896,-0.023501,0.002251,-0.059014,-0.017909,-0.074175,1.000000,-0.003675,-0.118607,0.047804,0.072114,-0.150441,-0.108078,-0.141253,-0.049109,-0.176505,-0.004900,-0.013028,0.008921,0.023872,-0.019679,0.021926,-0.004098,-0.013714,-0.000239,-0.000765,-0.026632,0.021879,-0.001073,0.025782,-0.025625
JobSatPoints_7,-0.006626,-0.053057,-0.049423,-0.016082,-0.004786,0.018428,-0.000982,0.004928,0.027359,-0.024115,0.019768,0.000577,0.015624,-0.024286,-0.005793,-0.014269,0.013315,0.001225,0.033569,-0.009596,-0.006480,0.032510,0.015446,-0.018526,-0.121147,-0.063764,-0.003675,1.000000,-0.158145,0.132851,-0.023037,-0.153843,-0.105724,-0.131068,-0.047777,-0.192314,0.006026,0.008821,0.009393,0.022455,0.002580,0.001308,0.003519,-0.010528,0.010288,0.008346,-0.001622,0.005753,0.006570,-0.004530,-0.053326
JobSatPoints_8,-0.022493,0.057389,0.060427,0.003773,0.027722,0.000336,0.010960,0.016824,-0.045307,0.027830,0.012475,0.034937,0.004134,0.012757,0.017929,0.003156,0.008444,0.025319,0.022076,0.000486,0.006489,-0.010550,0.013527,-0.156208,-0.069027,-0.112632,-0.118607,-0.158145,1.000000,-0.177365,-0.118658,0.131887,-0.086015,-0.035257,-0.018332,0.000855,0.003966,0.004291,-0.007574,0.027649,0.010804,0.029524,-0.009619,0.007403,-0.029127,-0.007858,0.008435,0.022944,0.023389,0.015846,0.042386
JobSatPoints_9,-0.031914,-0.063854,-0.076135,-0.000511,-0.031066,0.042675,0.047693,0.017727,0.027376,-0.026012,0.059406,0.004524,0.066632,-0.005157,0.008301,0.024691,0.036281,0.016548,0.040910,0.031393,0.005418,0.021409,0.066587,-0.030678,-0.132101,-0.094822,0.047804,0.132851,-0.177365,1.000000,0.063736,-0.127031,-0.124914,-0.140709,-0.041880,-0.219799,0.021430,0.006030,0.002332,0.012445,0.010955,0.011294,0.035100,0.012611,0.037084,0.025153,0.007726,0.001127,0.063483,-0.012186,-0.059164
JobSatPoints_10,-0.042555,-0.009494,0.013133,0.126015,0.014384,0.007814,0.036575,-0.019960,0.021230,0.022693,-0.005148,-0.021204,-0.000231,0.114956,0.012222,0.004481,0.019624,-0.000570,-0.020979,-0.006434,0.159028,-0.055814,-0.000827,-0.067207,-0.071126,-0.081002,0.072114,-0.023037,-0.118658,0.063736,1.000000,-0.071218,-0.121240,-0.107222,-0.065224,-0.192723,0.016777,0.019543,-0.003041,0.039664,-0.021862,0.011360,0.001780,0.024399,0.009856,0.013929,-0.005915,0.070841,0.027343,0.015690,-0.033561
JobSatPoints_11,-0.001402,0.030898,0.022734,-0.014028,0.052534,0.022742,-0.051687,0.040341,-0.055474,-0.003219,0.041233,0.083690,-0.002762,-0.030161,0.017581,0.008136,0.031648,0.069673,0.020263,0.045128,0.007742,-0.052586,0.008340,-0.142502,-0.081176,-0.161642,-0.150441,-0.153843,0.131887,-0.127031,-0.071218,1.000000,-0.099542,-0.022741,-0.006397,-0.030060,0.006985,0.005633,-0.006222,0.014090,0.025254,-0.017545,0.010421,0.025229,-0.001215,-0.001753,0.031258,-0.011656,0.027290,-0.047710,0.075329
JobSatPoints_13,-0.059533,0.014754,0.004061,0.039312,0.010861,0.014001,0.016537,0.024523,0.041673,0.055502,-0.001776,0.004990,0.061677,0.063228,0.039096,0.016328,0.027157,0.005608,0.007843,0.014417,0.013152,0.058957,0.081637,-0.136966,-0.082882,-0.043521,-0.108078,-0.105724,-0.086015,-0.124914,-0.121240,-0.099542,1.000000,0.209349,-0.035337,-0.065606,0.011873,0.004866,-0.003255,0.013866,-0.011135,0.021793,0.018222,0.014442,0.020132,0.039140,0.046693,0.023438,0.069076,0.010561,0.014629
JobSatPoints_14,-0.080407,0.015468,0.023473,0.089464,0.011865,-0.006746,0.027437,0.020180,0.011710,0.084227,-0.000577,0.017038,0.061691,0.113623,0.030324,0.020941,0.033635,0.030423,0.000331,0.010944,0.048414,0.021905,0.063685,-0.155594,-0.089147,-0.059365,-0.141253,-0.131068,-0.035257,-0.140709,-0.107222,-0.022741,0.209349,1.000000,-0.048356,-0.017402,0.002339,0.000540,-0.007402,0.021340,-0.020704,0.043427,-0.014866,0.029178,0.019249,0.033370,0.029585,0.079434,0.078783,0.014838,0.009344
JobSatPoints_15,0.008695,-0.029113,-0.041949,-0.061748,-0.021203,-0.016015,-0.016610,-0.013748,0.006122,-0.026949,-0.023911,0.017114,0.176736,-0.053817,-0.016834,-0.019980,-0.025367,0.004445,-0.001251,0.007849,-0.057463,0.021585,0.157974,-0.015948,-0.073056,-0.046925,-0.049109,-0.047777,-0.018332,-0.041880,-0.065224,-0.006397,-0.035337,-0.048356,1.000000,0.001085,-0.075865,-0.072228,-0.051283,-0.022397,0.007933,-0.025321,0.026377,-0.020090,-0.004415,0.002596,0.005148,-0.035248,0.103955,-0.004714,0.030365
JobSatPoints_16,0.058332,0.014112,-0.000396,-0.065896,0.002685,-0.041380,-0.077272,0.000275,-0.043197,0.017504,-0.031153,0.038446,-0.029305,-0.069084,-0.033655,-0.002006,-0.051369,0.016978,-0.012521,0.003972,-0.084423,0.007639,-0.042476,-0.086333,-0.007619,-0.090713,-0.176505,-0.192314,0.000855,-0.219799,-0.192723,-0.030060,-0.065606,-0.017402,0.001085,1.000000,0.003929,0.009443,0.012913,-0.035013,0.020464,-0.017864,0.008306,-0.018255,-0.042578,-0.037272,-0.001405,-0.049471,-0.041730,-0.018954,-0.009289
ToolCountWork,0.005409,0.054826,0.047317,-0.001117,0.014792,0.013738,-0.007001,-0.000075,0.004292,-0.000294,0.006279,0.007691,-0.059838,0.002815,-0.000471,0.004143,-0.004553,0.022020,0.002001,-0.003724,0.007932,-0.003121,-0.047994,-0.013704,-0.008486,-0.005454,-0.004900,0.006026,0.003966,0.021430,0.016777,0.006985,0.011873,0.002339,-0.075865,0.003929,1.000000,0.598456,0.002175,0.003594,0.016837,-0.010244,0.012294,0.018615,0.003876,-0.005391,0.000354,-0.014790,-0.058009,0.009045,0.001874
ToolCountPersonal,0.009398,0.082002,0.061273,0.003620,0.022496,0.013840,-0.011791,0.005736,-0.021373,-0.002312,0.002644,0.014857,-0.044483,0.002697,0.003281,-0.002054,0.004054,0.016225,0.004928,-0.001919,0.022172,-0.018808,-0.048062,-0.020199,-0.003729,0.003233,-0.013028,0.008821,0.004291,0.006030,0.019543,0.005633,0.004866,0.000540,-0.072228,0.009443,0.598456,1.000000,0.015097,0.010385,0.013595,-0.011414,0.013286,0.020496,-0.007006,-0.005016,-0.011223,-0.004633,-0.050363,0.003247,-0.007440