In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('../survey_results_public_2020.csv', index_col='Respondent')

The shape() method returns a tuple with the count of rows and columns. So, we have 64461 rows and 60 columns in the data set.

In [5]:
df.shape

(64461, 60)

To view the first five rows of the data set we will use the head method.

In [6]:
df.head()

,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,Yes,NaN,13,Monthly,NaN,NaN,Germany,European Euro,EUR,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core,ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,50.0,36,27
2,I am a developer by profession,No,NaN,19,NaN,NaN,NaN,United Kingdom,Pound sterling,GBP,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,NaN,7,4
3,I code primarily as a hobby,Yes,NaN,15,NaN,NaN,NaN,Russian Federation,NaN,NaN,...,Neither easy nor difficult,Appropriate in length,NaN,NaN,NaN,NaN,Somewhat more welcome now than last year,NaN,4,NaN
4,I am a developer by profession,Yes,25.0,18,NaN,NaN,NaN,Albania,Albanian lek,ALL,...,NaN,NaN,No,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat less welcome now than last year,40.0,7,4
5,"I used to be a developer by profession, but no...",Yes,31.0,16,NaN,NaN,NaN,United States,NaN,NaN,...,Easy,Too short,No,"Computer science, computer engineering, or sof...",Django;Ruby on Rails,Ruby on Rails,Just as welcome now as I felt last year,NaN,15,8

Our data set is locked and loaded lets start the fun.

Column condition filter
Let’s extract data based on the condition of when the salary is more than 40000 USD dollars in the ConvertedComp column.

In [7]:
df['ConvertedComp'] > 40000

Respondent
1        False
2        False
3        False
4        False
5        False
         ...
64858    False
64867    False
64898    False
64925    False
65112    False
Name: ConvertedComp, Length: 64461, dtype: bool

The output gives boolean values instead of records. It means where it finds condition is matched, it returns True, and if not, it returns False.

In order to get rows with data that meets our condition, we have to apply the condition in a data frame, and this will give us our expected result.

In [9]:
df[df['ConvertedComp'] > 40000]

,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,
8,I am a developer by profession,Yes,36.0,12,Yearly,116000.0,116000.0,United States,United States dollar,USD,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Django;React.js;Vue.js,Flask,Just as welcome now as I felt last year,39.0,17,13
11,I am a developer by profession,Yes,23.0,13,Yearly,31000.0,40070.0,United Kingdom,Pound sterling,GBP,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular;Django;React.js,Angular;Angular.js;Django;React.js,Just as welcome now as I felt last year,40.0,10,2
14,I am a developer by profession,Yes,27.0,13,Yearly,66000.0,66000.0,United States,United States dollar,USD,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular;Vue.js,Angular;Vue.js,Just as welcome now as I felt last year,40.0,5,1
16,I am a developer by profession,Yes,45.0,8,Monthly,7000.0,108576.0,United Kingdom,Pound sterling,GBP,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,jQuery;React.js,Just as welcome now as I felt last year,50.0,37,23
17,I am a developer by profession,Yes,25.0,14,Yearly,79000.0,79000.0,United States,United States dollar,USD,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core;Gatsby;React.js;Vue.js,ASP.NET;Gatsby;jQuery;React.js;Vue.js,Just as welcome now as I felt last year,40.0,7,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65596,I am a developer by profession,Yes,NaN,22,Yearly,70000.0,70000.0,United States,United States dollar,USD,...,NaN,NaN,NaN,Web development or web design,NaN,Angular.js;Django;jQuery;React.js;Ruby on Rails,A lot more welcome now than last year,40.0,6,4
65598,"I am not primarily a developer, but I write co...",Yes,NaN,6,Yearly,52000.0,67215.0,United Kingdom,Pound sterling,GBP,...,NaN,NaN,NaN,Mathematics or statistics,NaN,NaN,NaN,70.0,37,NaN
65602,"I am not primarily a developer, but I write co...",Yes,NaN,13,Yearly,140000.0,140000.0,United States,United States dollar,USD,...,NaN,NaN,NaN,"Another engineering discipline (such as civil,...",NaN,NaN,NaN,NaN,15,12
65604,I am a developer by profession,No,NaN,13,Weekly,3000.0,150000.0,United States,United States dollar,USD,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,NaN,45.0,7,4
65617,I am a developer by profession,Yes,NaN,15,Yearly,120000.0,129718.0,Germany,European Euro,EUR,...,NaN,NaN,NaN,"Another engineering discipline (such as civil,...",NaN,NaN,Just as welcome now as I felt last year,35.0,9,9

Column and row condition filter
We can also pass conditions with the loc and iloc methods, which is a more convenient way to filter out the data because we can get only those rows & columns we are interested.

This time we create the same condition but assign it in a variable (high_salary_filter) that increases the readability, and our code looks better.

In [10]:
high_salary_filter = df['ConvertedComp'] > 40000

Now we will pass our condition to the loc method and select only three columns — Country , ConvertedComp, LanguageWorkedWith

In [12]:
df.loc[high_salary_filter, ['Country', 'ConvertedComp', 'LanguageWorkedWith']]

,Country,ConvertedComp,LanguageWorkedWith
Respondent,,,
8,United States,116000.0,Python;SQL
11,United Kingdom,40070.0,C#;JavaScript;Swift
14,United States,66000.0,HTML/CSS;JavaScript;SQL;TypeScript
16,United Kingdom,108576.0,Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...
17,United States,79000.0,C#;HTML/CSS;JavaScript;Python;SQL;VBA
...,...,...,...
65596,United States,70000.0,JavaScript;Python;TypeScript
65598,United Kingdom,67215.0,NaN
65602,United States,140000.0,NaN
65604,United States,150000.0,NaN
65617,Germany,129718.0,NaN

The output gives a concise result that meets both row and column requirements.

Inverted condition filter
~ : Tilde (~) is a Python negation operator which reverses the condition. For example, ~ON becomes OFF.

Now, if we want to see the developer whose salary of less than 40000, instead of writing the condition again, we just put a ~ operator on a high_salary_filt (~ high_salary_filt). Isn’t that awesome….

In [13]:
df.loc[~ high_salary_filter, ['Country', 'ConvertedComp', 'LanguageWorkedWith']].head(20)

,Country,ConvertedComp,LanguageWorkedWith
Respondent,,,
1,Germany,NaN,C#;HTML/CSS;JavaScript
2,United Kingdom,NaN,JavaScript;Swift
3,Russian Federation,NaN,Objective-C;Python;Swift
4,Albania,NaN,NaN
5,United States,NaN,HTML/CSS;Ruby;SQL
6,Germany,NaN,HTML/CSS;Java;JavaScript
7,India,NaN,C#;HTML/CSS;PHP
9,Tunisia,NaN,HTML/CSS;JavaScript;PHP
10,United Kingdom,32315.0,HTML/CSS;Java;JavaScript;Python;SQL
12,Spain,14268.0,HTML/CSS;JavaScript
13,Netherlands,38916.0,C;JavaScript;Python
15,France,NaN,Bash/Shell/PowerShell;C;HTML/CSS;Java;Python;SQL
20,Spain,NaN,Java;JavaScript;SQL
21,Belgium,NaN,Bash/Shell/PowerShell;C#;HTML/CSS;Java;JavaScr...
22,India,NaN,Java;Python
23,Germany,NaN,Bash/Shell/PowerShell;C#;C++
25,Portugal,NaN,Bash/Shell/PowerShell;C
27,United States,NaN,Bash/Shell/PowerShell;C;C++;Java;Python;SQL
28,China,NaN,Python;R
29,Ukraine,NaN,C#;C++;HTML/CSS;Python

NaN means Null Values. It means respondents did not answer this question or they are students with no salary.

Important to remember here is that NaN is considered a value less than the stated value. Apart from this, we only got those developers whose salary is less than 40000.

Complex filter using multiple conditions
This section will use Logical (AND, OR) Operators. Before jumping to the complex filtering, I want to introduce you to logical operators AND and OR operators.

AND: It returns TRUE only if all conditions are true.
OR: It returns TRUE only if either one operand is true.
In Pandas, & is equal to AND and | is equivalent to OR
In our example, the filter is defined as follows:

Salary of greater than 50000 in ConvertedComp

AND

The Country column should contain value to the United States

AND

LanguageWorkedWith column string values contain ‘Python.’ — (we will use str. contains() method for this condition. This is a new method we are learning here. It is used to test if a pattern or sub string is contained within a string value.)

All these conditions will be applied to the loc method as a filter, and the rows that meet the requirements should return columns ‘Country’, ‘ConvertedComp’, ‘LanguageWorkedWith’.

In [15]:
filt = ((df['ConvertedComp'] > 50000) & (df['Country'] == 'United States')) | (df['LanguageWorkedWit'].str.contains('Python'))
df.loc[filt, ['Country', 'ConvertedComp', 'LanguageWorkedWith']].head(50)

KeyError: 'LanguageWorkedWit'

In [16]:
filt = ((df['ConvertedComp'] > 50000) & (df['Country'] == 'United States')) | (df['LanguageWorkedWith'].str.contains('Python', na=False))

df.loc[filt, ['Country', 'ConvertedComp', 'LanguageWorkedWith']].head(50)

,Country,ConvertedComp,LanguageWorkedWith
Respondent,,,
3,Russian Federation,NaN,Objective-C;Python;Swift
8,United States,116000.0,Python;SQL
10,United Kingdom,32315.0,HTML/CSS;Java;JavaScript;Python;SQL
13,Netherlands,38916.0,C;JavaScript;Python
14,United States,66000.0,HTML/CSS;JavaScript;SQL;TypeScript
15,France,NaN,Bash/Shell/PowerShell;C;HTML/CSS;Java;Python;SQL
17,United States,79000.0,C#;HTML/CSS;JavaScript;Python;SQL;VBA
18,United States,1260000.0,Bash/Shell/PowerShell;HTML/CSS;Perl
19,United States,83400.0,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;S...
22,India,NaN,Java;Python
26,Canada,71093.0,JavaScript;Python
27,United States,NaN,Bash/Shell/PowerShell;C;C++;Java;Python;SQL
28,China,NaN,Python;R
29,Ukraine,NaN,C#;C++;HTML/CSS;Python
30,United Kingdom,38778.0,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;P...
32,Canada,31764.0,C;C++;Java;Python;SQL;VBA
36,United Kingdom,77556.0,C#;Go;HTML/CSS;Java;JavaScript;Python;R;SQL
38,Italy,97288.0,HTML/CSS;JavaScript;Python;Ruby;Rust
39,United Kingdom,NaN,C#;Python
40,United States,NaN,C;C#;C++;HTML/CSS;JavaScript;PHP;Python;SQL
41,United States,106000.0,C;C#;Java;SQL
42,United States,130000.0,Bash/Shell/PowerShell;C#;HTML/CSS;Java;JavaScr...
43,United States,135000.0,Dart;HTML/CSS;Java;JavaScript;SQL
44,Brazil,55893.0,HTML/CSS;Python;R;SQL;VBA
45,France,36753.0,Bash/Shell/PowerShell;C;C++;Java;JavaScript;Py...
47,United Kingdom,74970.0,Bash/Shell/PowerShell;C#;Java;JavaScript;Pytho...
48,United States,125000.0,JavaScript;Ruby;SQL
49,United States,52000.0,C#;HTML/CSS;JavaScript;TypeScript
51,Canada,103615.0,JavaScript;Python;SQL;TypeScript
53,United States,NaN,Dart;HTML/CSS;Python
54,United States,160000.0,C#;HTML/CSS;JavaScript
55,United States,NaN,Python
56,United States,NaN,HTML/CSS;JavaScript;PHP;Python;SQL;TypeScript
57,United States,1620000.0,C#;VBA
60,Germany,NaN,C#;HTML/CSS;Java;JavaScript;Python;SQL
62,United Kingdom,NaN,C#;C++;HTML/CSS;Java;Python;Ruby;SQL;Swift
63,India,NaN,C;C++;HTML/CSS;Java;JavaScript;Python
65,United States,1176000.0,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;SQL
66,Canada,NaN,Bash/Shell/PowerShell;C;C#;C++;HTML/CSS;Java;J...
67,United States,250000.0,HTML/CSS;JavaScript;Ruby
68,United States,NaN,Assembly;Bash/Shell/PowerShell;C;C#;HTML/CSS;J...
69,France,594539.0,HTML/CSS;Python
72,United States,NaN,Bash/Shell/PowerShell;JavaScript;Python;Swift
75,Canada,NaN,Bash/Shell/PowerShell;HTML/CSS;JavaScript;Python
76,United States,NaN,Assembly;Bash/Shell/PowerShell;C;C++;Python
77,United States,NaN,C++;HTML/CSS;Java;Python;R
80,United States,94500.0,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;P...
81,United States,NaN,Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;...
82,United States,117000.0,C#;HTML/CSS;JavaScript;SQL
83,Poland,3036.0,C;C++;HTML/CSS;Python

Let’s do another example; if we want to analyze the rows belonging to three Asian countries, we can create a filter using the OR (|) condition that filters out the rows belonging to three Asian Countries (India,China,Indonesia).

In [17]:
Asia_country = (df['Country'] == 'India') | (df['Country'] == 'China') | (df['Country'] == 'Indonesia')

Now we are storing this data into another variable and printing the first five rows of it.

In [18]:
Asian_df = df.loc[Asia_country]
Asian_df.head()

,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,
7,I am a developer by profession,Yes,NaN,18,Monthly,NaN,NaN,India,United States dollar,USD,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,A lot more welcome now than last year,NaN,6,4
22,I am a developer by profession,Yes,NaN,18,Monthly,NaN,NaN,India,Indian rupee,INR,...,Easy,Appropriate in length,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,50.0,10,2
28,I am a student who is learning to code,Yes,NaN,22,NaN,NaN,NaN,China,NaN,NaN,...,Neither easy nor difficult,Too long,No,"A health science (such as nursing, pharmacy, r...",NaN,NaN,Just as welcome now as I felt last year,NaN,2,NaN
58,I am a developer by profession,Yes,NaN,22,NaN,NaN,NaN,India,Indian rupee,INR,...,Neither easy nor difficult,Too long,NaN,Web development or web design,Angular;Angular.js;ASP.NET;ASP.NET Core;jQuery,Angular;Angular.js;ASP.NET;ASP.NET Core;jQuery,NaN,NaN,NaN,NaN
63,I am a student who is learning to code,Yes,21.0,17,NaN,NaN,NaN,India,NaN,NaN,...,Easy,Appropriate in length,No,NaN,Angular.js;Django;jQuery;Laravel;Vue.js,NaN,Not applicable - I did not use Stack Overflow ...,NaN,4,NaN

The output contains rows with unique values of the country column (China, India, Indonesia). Let’s use the unique method to verify our result.

In [19]:
df.loc[Asia_country, 'Country'].unique()

array(['India', 'China', 'Indonesia'], dtype=object)

Bonus Section
So far, we saw multiple conditions using the OR (|) operator, which is very helpful but let suppose if we want to filter out 10 Asian Countries, it will be a very long syntax. At the same time, Python gives a great isin() operator, which checks whether values are contained in Series.

In other words, it shortens the OR condition.

In [20]:
Asia_country = df['Country'].isin(values = ['China', 'India', 'Indonesia']) # Passing a list to values parameter

now lets review the unique values

In [22]:
df.loc[Asia_country, 'Country'].unique()

array(['India', 'China', 'Indonesia'], dtype=object)

Interesting, you can see this is a fancy and less time-consuming way to write multiple OR conditions.